### ISSUE TITLE
Exception in thread "main" org.jsoup.HttpStatusException: HTTP error fetching URL. Status=502, URL=[http://www.xbiqugu.net/modules/article/waps.php]

### ISSUE THREAD

**Issue by z1991817** [pcdd-group/so-novel#7]
Exception in thread "main" org.jsoup.HttpStatusException: HTTP error fetching URL. Status=502, URL=[http://www.xbiqugu.net/modules/article/waps.php]
<img width="588" alt="image" src="https://github.com/pcdd-group/so-novel/assets/14747878/18eb2a6f-432b-4714-894b-cc53e1b3d5cd">

**Comment by pcdd-group** [comment]
![image](https://github.com/pcdd-group/so-novel/assets/51998152/14b6c44b-9c6f-430d-a030-48e34a41eb18)

**Comment by z1991817** [comment]
我这个是哪里有问题吗？

**Comment by pcdd-group** [comment]
是最新版吗，检查下网络环境？先看网站能访问不：http://www.xbiqugu.net

**Comment by z1991817** [comment]
好了，谢谢
